Add login with GitHub
clojars/clojars-web pull request #762
Opened 2020-07-04 15:21 UTC by renatoalencar

Based on #728, I decided to try to build this. Initially I'm using `clj-social` as the lib to perform OAuth related tasks, and organize everything as a `com.cemerick/friend` workflow. I think this initial implementation is a little bit hacky, but I'm just trying to create a Proof of Concept in order to build a better implementation. I had to some some stuff around, mainly on the `clojars.web.user` namespace, but everything is working as it was before.

2020-11-01 16:22 UTC, tobias requested changes
Thanks @renatoalencar! I have a question and some feedback.

First, to test this (and later set this up in production) do I need to create a GitHub OAuth application to provide the API key & secret? 

Can you change the login page to have the GH login button below the existing one with an "Or" between them to help make it clear that you don't need to provide the username/password/token when logging in via GitHub? 

Something like this:

<img width="670" alt="Login - Clojars 2020-11-01 11-09-18" src="https://user-images.githubusercontent.com/2631/97808358-79aa1980-1c34-11eb-813e-c04e0bc1185e.png">

2020-11-01 19:48 UTC, renatoalencar commented
You would need to create an OAuth application on GitHub and set the credentials on your production `config.edn`. I left an empty example on `resources/default_config.edn`. The unit tests run without any config, but in order to test it on your browser you need to set this up. I cited above on:

> Needs to add :github-api-key, :github-api-secret and optionally :github-callback-uri (it has to be configured on GitHub anyway).

2020-11-01 20:06 UTC, renatoalencar commented
Made the change, thank you for the review, @tobias.

2020-11-01 22:07 UTC, tobias requested changes
Thanks for the update. I created an OAuth app and tested this a bit. I ran in to a few issues (see comments), but I think this is really close!

2020-11-01 22:07 UTC, tobias commented on src/clojars/friend/github.clj
> +               :flash "Your primary e-mail is not registered")))))
I think we want to grab all emails from github, filter out the non-verified ones, then try them each until we find one that exists in the clojars db. For me, my primary email in GitHub isn't my clojars email, but my clojars email is listed (and verified) in my github account.

2020-11-01 22:07 UTC, tobias commented on src/clojars/friend/github.clj
> +  (let [code (-> req :params :code)
This assumes that the code is always in the response, but if it isn't, we throw an NPE in the call to `access-token`. This can happen if the user cancels the authorization. In that case, GitHub calls the callback with:

```
/oauth/github/callback?error=access_denied&error_description=The+user+has+denied+your+application+access.&error_uri=https%3A%2F%2Fdocs.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23access-denied
```

2020-11-01 22:07 UTC, tobias commented on src/clojars/github.clj
> +    (.getAuthorizationUrl service))
I had to add a scope to this request for it to generate a token that would allow me to use the `/user/emails` endpoint:

```suggestion
    (.getAuthorizationUrl service {"scope" "user:email"}))
```

2020-11-01 22:30 UTC, renatoalencar commented on src/clojars/friend/github.clj
> +               :flash "Your primary e-mail is not registered")))))
That's great, I initially thought to use only the primary one to simplify, but as you pointed out it would be better checking no all the verified ones.

2020-11-01 22:31 UTC, renatoalencar commented on src/clojars/friend/github.clj
> +  (let [code (-> req :params :code)
That's a interesting edge case, I'll do some research on that in order to understand the better way to handle this.

2020-11-01 22:33 UTC, renatoalencar commented on src/clojars/github.clj
> +    (.getAuthorizationUrl service))
I added this on directly on GitHub, but it would be better if explicitly on the code.

2020-11-02 00:15 UTC, renatoalencar commented on src/clojars/friend/github.clj
> +               :flash "Your primary e-mail is not registered")))))
I changed this, could you also review the tests, please?

2020-11-02 00:55 UTC, renatoalencar commented on src/clojars/friend/github.clj
> +  (let [code (-> req :params :code)
I read the GitHub [documentation](https://docs.github.com/en/free-pro-team@latest/developers/apps/troubleshooting-authorization-request-errors) about that, and it lists some other errors that can happen. I updated the code to handle that.

For the `access_denied` error it just inform the user and for the other error it throws an exception so that you can be aware of these unexpected cases.

2020-11-02 00:55 UTC, renatoalencar commented on src/clojars/friend/github.clj
> +  (let [code (-> req :params :code)
Let me know what you think about that.

2020-11-02 12:29 UTC, tobias requested changes
I added a couple of comments, but I think the only blocking one is the one on the tests. 

Regarding:

> I added this on directly on GitHub, but it would be better if explicitly on the code.

I didn't see a place to add it on the GitHub side for an OAuth application. Where did you add it? I agree that I like having the scope in the request, but I'm curious about how to do it from the GitHub side.

2020-11-02 12:29 UTC, tobias commented on test/clojars/unit/friend/github_test.clj
> +      (is (some? (-> response :headers (get "Location")))))))
I would verify here the location is what we expect, since it could be a redirect to the login page with an error and not the redirect to initialize the oauth flow.

2020-11-02 12:29 UTC, tobias commented on src/clojars/friend/github.clj
> +                 :flash "None of your e-mails are registered"))))))
You mentioned in Slack that you weren't happy with the deep nesting within this function. I'm dropping my feedback from there here as well:

You could instead write this as a pipeline-like process (untested):

```suggestion
(defn- handle-error [{:keys [params]}]
  (let [{:keys [error error_description]} params]
    (when error
      (if (= error "access_denied")
        (assoc (redirect "/login")
               :flash "You declined access to your account")
        (throw (Exception. (str (-> req :params :error_description))))))))

(defn- get-emails [{:keys [params] ::keys [service]}]
  (let [code (:code params)
        token (github/access-token service code)
        emails (github/get-verified-emails service token)]
    (if (seq emails)
      {::emails emails}
      (assoc (redirect "/login")
             :flash "No verified e-mail was found"))))

(defn- find-user [{::keys [db emails]}]
  (if-let [user (db/find-user-by-email-in db emails)]
    {::user user}
    (assoc (redirect "/register")
           :flash "None of your e-mails are registered")))

(defn- make-auth [::keys [user]]
  (let [username (:user user)]
    (workflow/make-auth {:identity username :username username})))

(defn callback [req service db]
  (reduce (fn [acc f]
            (let [res (merge acc (f acc))]
              (if (:status res)
                ;; exit early if given a ring response
                (reduced res)
                res)))
          (assoc req
                 ::db db
                 ::service service)
          [handle-error
           get-emails
           find-user
           make-auth]))
```

Though that may not be clearer. A less drastic solution would be to break this up into smaller functions but keep the nested if structure.

2020-11-03 03:19 UTC, renatoalencar commented
> I didn't see a place to add it on the GitHub side for an OAuth application. Where did you add it? I agree that I like having the scope in the request, but I'm curious about how to do it from the GitHub side.

I think I misunderstood something, I set this up a few months ago so I don't really remember how I did it. But it's working even if I didn't define any scope. Sorry for the misleading statement.

2020-11-03 03:22 UTC, renatoalencar commented on test/clojars/unit/friend/github_test.clj
> +      (is (some? (-> response :headers (get "Location")))))))
Great! I wanted this at first, but I couldn't define a way of setting this without testing the internals. But I guess I could just verify the domain based on a RegEx.

2020-11-03 03:28 UTC, renatoalencar commented on src/clojars/friend/github.clj
> +                 :flash "None of your e-mails are registered"))))))
I have a whole new perspective on how to structure this, thank you so much. I'll seek the Clojure docs to understand a clearer way to do this, but the concept solves exactly what I was frustrated about.

2020-11-04 02:55 UTC, renatoalencar commented on test/clojars/unit/friend/github_test.clj
> +      (is (some? (-> response :headers (get "Location")))))))
Did it

2020-11-04 03:00 UTC, renatoalencar commented on src/clojars/friend/github.clj
> +                 :flash "None of your e-mails are registered"))))))
Used your suggestion, but I had to tweak it around a little bit. The `workflow/make-auth` function adds metadata to the map, which is removed by the `merge` function. So, at the end of the reduction when the field `:identity` is present, `workflow/make-auth` is actually called. I thought about leaving it in the `make-auth` function, but I think it would look too much implicit. Let me know what you think.

2020-11-07 13:59 UTC, tobias approved these changes
This looks great, thanks! I left one comment just as feedback, but I'll go ahead and merge this as is and work on releasing it.

2020-11-07 13:59 UTC, tobias commented on test/clojars/unit/friend/github_test.clj
> +      (is (and (= identity "johndoe") (= username "johndoe")))))
You could write this a couple of other ways:

As separate assertions (with the expected value first). This allows the test to fail with the exact binding that is incorrect, and putting the expected value first matches `is`'s expectation about the order for reporting purposes:

```
(is (= "johndoe" identity))
(is (= "johndoe" username))
```

If you prefer having this as one assertion, you can use a single `=`:

```
(is (= "johndoe" identity username))
```

2020-11-07 13:59 UTC, merged

2020-11-07 21:20 UTC, renatoalencar commented on test/clojars/unit/friend/github_test.clj
> +      (is (and (= identity "johndoe") (= username "johndoe")))))
That's great, thanks for the feedback.